services:
  casino:
    build: .
    ports:
      - "5173:5173" # Web app A
      - "5174:5174" # Web app B
      - "5175:5175" # Web app C
      - "8080:8080" # faucet
      - "8081:8081" # GraphQL A
      - "8082:8082" # GraphQL B
      - "8083:8083" # GraphQL C
      - "9001:9001" # shard proxy
      - "13001:13001" # shard
    volumes:
      - .:/build

